workflow update

diff --git a/.github/workflows/releasebuild.yml b/.github/workflows/releasebuild.yml
--- a/.github/workflows/releasebuild.yml
+++ b/.github/workflows/releasebuild.yml
@@ -14,33 +14,32 @@ jobs:
       fail-fast: false
       matrix:
         language: [ 'go' ]
+    
     steps:
-      
-      steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
+    - name: Checkout repository
+      uses: actions/checkout@v4
 
-      - name: Setup Go
-        uses: actions/setup-go@v2
-        with:
-          go-version: ${{ matrix.go-version }}
-      
-      - name: "Build"
-        run: |
-          bash scripts/build-all-arch.sh
-        working-directory: "."
+    - name: Setup Go
+      uses: actions/setup-go@v2
+      with:
+        go-version: ${{ matrix.go-version }}
+    
+    - name: "Build"
+      run: |
+        bash scripts/build-all-arch.sh
+      working-directory: "."
 
-      - name: "Test"
-        run: | 
-          set -e
-          apt-get install -y buildah
-          for exe in devc-v* ; do echo -e "\nTesting $exe"; if ! ./$exe --version ; then echo "Error executing : $exe" ; exit 1; fi; done ;
-        working-directory: "."
+    - name: "Test"
+      run: | 
+        set -e
+        apt-get install -y buildah
+        for exe in devc-v* ; do echo -e "\nTesting $exe"; if ! ./$exe --version ; then echo "Error executing : $exe" ; exit 1; fi; done ;
+      working-directory: "."
 
-      - uses: "marvinpinto/action-automatic-releases@latest"
-        with:
-          repo_token: "${{ secrets.GITHUB_TOKEN }}"
-          prerelease: false
-          files: |
-            LICENSE
-            devc-v*
+    - uses: "marvinpinto/action-automatic-releases@latest"
+      with:
+        repo_token: "${{ secrets.GITHUB_TOKEN }}"
+        prerelease: false
+        files: |
+          LICENSE
+          devc-v*
